grav = 0;
hsp = 0;
vsp = 0;
grounded = false;
image_speed = 0;
alarm[0] = 40;
global.panic = false;
alarm[1] = 500;
platformid = -4;
hsp_carry = 0;
vsp_carry = 0;
global.combo = 0;
global.comboscore = 0;
instance_destroy(obj_comboend);
